modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/ShayBox/KillEffects/issues"
license = "MIT"

[[mods]]
modId = "killeffects"
version = "${version}"
displayName = "KillEffects"
authors = "ShayBox"
description = '''
Client side player kill effects
'''
logoFile = "assets/killeffects/icon.png"

[[dependencies.killeffects]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.killeffects]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "killeffects.mixins.json"
